{
 "title": "Ultimate Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime Percent",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(rate(istiod_uptime_seconds{namespace=\"istio-system\"}[1m]), 0.01) * 100",
     "legendFormat": "uptime percent"
    }
   ]
  },
  {
   "title": "Requests/second",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total[1m]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes)) / 28800884736",
     "legendFormat": "sum(container_memory_working_set_bytes) / machine_memory_bytes"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total[1m]))",
     "legendFormat": "CPU Usage total"
    },
    {
     "expr": "irate(process_cpu_seconds_total{app=\"istiod\"}[1m])"
    },
    {
     "expr": "(irate(container_cpu_usage_seconds_total[1m]))/100"
    }
   ]
  },
  { "title": "Service Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Requests/second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\"}[1m]))",
     "legendFormat": "total requests"
    },
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\", response_code=~\"2.*\"}[1m]))",
     "legendFormat": "successful requests"
    },
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\", response_code=~\"5.*\"}[1m]))",
     "legendFormat": "failed requests (status 5xx)"
    },
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\", response_code=~\"4.*\"}[1m]))",
     "legendFormat": "failed requests (status 4xx)"
    }
   ]
  },
  {
   "title": "Requests/second",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(istio_requests_total{reporter=\"source\", response_code=~\"2.*\"}[1m])) + sum(rate(istio_requests_total{reporter=\"source\", response_code=~\"3.*\"}[1m])))/sum(rate(istio_requests_total{reporter=\"source\"}[1m]))",
     "legendFormat": "successful requests"
    },
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\", response_code=~\"5.*\"}[1m]))/sum(rate(istio_requests_total{reporter=\"source\"}[1m]))",
     "legendFormat": "failed requests (status 5xx)"
    },
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\", response_code=~\"4.*\"}[1m]))/sum(rate(istio_requests_total{reporter=\"source\"}[1m]))",
     "legendFormat": "failed requests (status 4xx)"
    }
   ]
  },
  {
   "title": "Total bytes / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(irate(istio_response_bytes_sum{source_workload=\"istio-ingressgateway\", reporter=\"source\"}[1m])) / 1000",
     "legendFormat": "ingress"
    },
    {
     "expr": "(sum(irate(istio_response_bytes_sum{source_workload_namespace!=\"istio-system\", reporter=\"source\"}[1m])) + sum(irate(istio_request_bytes_sum{source_workload_namespace!=\"istio-system\", reporter=\"source\"}[1m]))) / 1000",
     "legendFormat": "proxy"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(rate(istio_request_duration_milliseconds_count[5m]))"
    }
   ]
  },
  {
   "title": "HTTP/GRPC Workloads",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "label_join(sum(rate(istio_requests_total{reporter=\"source\", response_code=\"200\"}[1m])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((sum(rate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\"}[1m])) by (destination_workload, destination_workload_namespace) / sum(rate(istio_requests_total{reporter=\"source\"}[1m])) by (destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    }
   ]
  }
 ]
}